version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.8-browsers

    steps:
      - checkout
      - run: echo 'export PATH=${HOME}/${CIRCLE_PROJECT_REPONAME}/node_modules/.bin:$PATH' >> $BASH_ENV
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Run tests
<<<<<<< HEAD
          command: yarn cypress:run
=======
          command: yarn test
>>>>>>> 02a7d803ec998e286f0f76fe54a6de05d1da036c
      - run:
          name: Run linter
          command: yarn lint

      - save_cache:
          key: dependency-cache
          paths:
            - ~/.cache/yarn