version: 2
jobs:
  build:
    docker:
      - image: cypress/base:10
    steps:
      - checkout
      - restore_cache:
          name: Restore yarn and Cypress cache
          keys:
            - dependencies
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: dependencies
          paths:
            - ~/.cache
      - run:
          name: Run web server
          command: npm start
          background: true
      - run:
          name: Run tests
          command: yarn cypress:record
      - run:
          name: Run linter
          command: yarn lint