version: 2
jobs:
  build:
    docker:
      - image: cypress/node:9.8-browsers
    steps:
      - checkout
      - run: echo 'export PATH=${HOME}/${CIRCLE_PROJECT_REPONAME}/node_modules/.bin:$PATH' >> $BASH_ENV
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Run web server
          command: yarn start
          background: true
      - run:
          name: Verify Cypress
          command: yarn cy:verify
      - run:
          name: Run tests
          command: yarn cypress
      - run:
          name: Run linter
          command: yarn lint
      - save_cache:
          key: dependency-cache
          paths:
            - ~/.cache/yarn